from pathlib import Path
root=Path(__file__).resolve().parents[1]
end=(root/'afk_endgame.go').read_text()
pol=(root/'afk_polish.go').read_text()
hud=(root/'afk_bottom_hud.go').read_text()
main=(root/'main.go').read_text()
sing=(root/'afk_singularity.go').read_text()
checks=[]
def c(n,x): checks.append((n,bool(x)))
c('section11 persistence','AFKSection11Complete' in main and 'AFKPrestigeRank' in main)
c('prestige after section10','AFKSection10Complete' in end)
c('10 hard coded prestige ranks','afkPrestigeMaxRank = 10' in end and 'afkPrestigeCosts' in end)
c('prestige permanent production','afkPrestigeMultiplierMilli' in end and '+5%' in end)
c('prestige does not reset facilities','FACILITIES AND UPGRADES ARE NEVER RESET' in end)
c('prestige bottom tab','"PRESTIGE"' in hud)
c('prestige input guarded','afkActionAllowed("prestige"' in end)
c('prestige spend helper','afkSpendStarbits(c)' in end)
c('section12 persistence','AFKSection12Complete' in main)
c('milestone queue','afkQueueMilestone' in pol)
c('milestone duplicate suppression','identical banners' in pol)
c('milestone visual no economy mutation','AFKStarbits' not in pol)
c('milestone draw integrated','drawAFKMilestoneBanner' in sing)
c('prestige draw integrated','drawAFKPrestige' in sing)
c('endgame objective integrated','afkSection11Objective' in sing)
for n,v in checks: print(('PASS' if v else 'FAIL')+' - '+n)
print(f"\n{sum(v for _,v in checks)}/{len(checks)} Sections 11-12 assertions passed")
raise SystemExit(0 if all(v for _,v in checks) else 1)
