from pathlib import Path
root=Path(__file__).resolve().parents[1]
main=(root/'main.go').read_text(errors='ignore')
resp=(root/'survival_respawn.go').read_text(errors='ignore')
clar=(root/'afk_clarity.go').read_text(errors='ignore')
exp=(root/'afk_expeditions.go').read_text(errors='ignore')
end=(root/'endurance_render_d2d.go').read_text(errors='ignore')
checks=[]
def ck(name,cond):
    print(('PASS' if cond else 'FAIL')+' - '+name); checks.append(bool(cond))
ck('v431 build identity', 'clientBuildVersion = "v431"' in (root/'build_identity.go').read_text())
ck('failed/revive state keeps visible cursor', 'if state != StatePlaying || overlayMode != OverlayNone' in main)
ck('revive footer simplified', 'CLICK ANYWHERE TO CONTINUE' in resp and 'CLICK ANYWHERE ELSE IN THE GAME AREA' not in resp)
ck('revive button has hover state', 'hover := pointInRect(cursorPos, b)' in resp and 'rgb(116, 76, 204)' in resp)
ck('revive restores full HP', 'survivalHP = survivalMaxHP()' in resp)
ck('revive uses nova bomb', 'survivalCollectPickup(survivalPickupBomb)' in resp)
ck('revive immunity remains three seconds', 'now.Add(3 * time.Second)' in resp)
ck('no-revive authoritative status can auto-continue', 'survivalRespawnStatusChecked' in resp and 'finishSurvivalFailure(h)' in resp[resp.index('func survivalRespawnProcessMainThread'):])
ck('cache moved farther right', 'left := cx + sx(180, w)' in exp)
ck('cache no rectangular outline frame', 'drawOutlineRect(hdc, RECT{img.Left' not in exp)
ck('cache uses silhouette trace buffers', 'starCacheTraceDim' in exp and 'starCacheTraceHot' in exp and 'makeTintedAlphaBGRA' in exp)
ck('cache trace buffers are cached', 'sync.Once' in exp and 'starCacheTraceOnce.Do' in exp)
ck('core T2 gate shows live missing scout checklist', 'func afkScoutDevelopmentSummary() string' in clar and 'SCOUT TIER %d/2' in clar and 'CACHE CHANCE LV.%d/3' in clar)
ck('disabled core action explains blocker', 'SCOUT DEVELOPMENT REQUIRED' in clar and 'NEED %s STARBITS' in clar)
ck('Endurance ships use pulse outline', 'func d2dDrawEnduranceShipPulseOutline' in end and 'd2dDrawEnduranceShipPulseOutline(shipBmp, dst, src, shipID)' in end)
ck('legacy rare aura is no longer called in ship render', 'd2dDrawRareGarageShipAura(x, y, shipID)' not in end)
ck('pulse outline applies all ships', 'Every ship gets the clean trace' in end)
ck('rarity only scales pulse strength', 'rareGarageShipGlowLevel(shipID)' in end and 'strength :=' in end)
print(f"\n{sum(checks)}/{len(checks)} v431 assertions passed")
raise SystemExit(0 if all(checks) else 1)
