from pathlib import Path
root=Path(__file__).resolve().parents[1]
t=(root/'afk_research_talents.go').read_text()
a=(root/'afk_research_assets.go').read_text()
e=(root/'afk_expeditions.go').read_text()
s=(root/'afk_singularity.go').read_text()
w=(root/'afk_world_buildings.go').read_text()
m=(root/'main.go').read_text()
d=(root/'afk_drones.go').read_text()
checks=[]
def ck(name, cond):
    checks.append((name,bool(cond)))
    print(('PASS' if cond else 'FAIL'), name)
ck('14 pilot skills', t.count('{"') >= 14 and 'STEALTH PROTOCOL' in t and 'OVERDRIVE EXTENSION' in t)
ck('slower point thresholds', '[]int{5, 12, 20, 30, 40, 50, 60, 70, 80, 90, 100}' in t)
ck('grandfather spent points', 'earned < gameMeta.AFKTalentPointsSpent' in t)
ck('three visual states', 'return "active"' in t and 'return "available"' in t and 'return "hidden"' in t)
ck('question mark shared asset', 'question_locked' in a)
ck('available uses locked art', 'iconState = "locked"' in t)
ck('future hides real art', 'afkSkillIconName(i, iconState)' in t and 'state == "hidden"' in a)
ck('gold pulse nodes', 'brightPulse' in t and 'afkRGBLerp' in t)
ck('gold pulse connectors', 'childState == "available"' in t and 'drawLineSimple' in t)
ck('left to right world', 'afkTalentVirtualSize' in t and '{1280, 315}' in t)
ck('drag pan', 'afkTalentPanDragging' in t and 'clampAFKTalentPan' in t)
ck('slide drawer', 'afkTalentInfoShownRect' in t and 'afkTalentInfoOpen' in t)
ck('empty closes drawer', 'Empty-space click closes the drawer' in t)
ck('nav talent applied', 'afkTalentNavRewardMultiplierMilli' in e)
ck('cache chance talents applied', e.count('afkTalentCacheChanceBonusPercent()') >= 2)
ck('drone talent applied', 'afkTalentDroneMultiplierMilli' in d)
ck('overdrive duration applied', 'afkTalentOverdriveDurationMultiplierMilli' in s)
ck('moon moved down 20', 'sy(27, hgt)' in w and 'sy(20, hgt)' in s)
ck('moon width overscan', 'overscan := sx(22, w)' in s)
ck('native cursor starbase only setcursor', 'the native Windows arrow belongs to Starbase only' in m)
ck('native cursor starbase only mousemove', 'keep the OS pointer visible only inside Starbase' in m)
ck('v437 identity', 'clientBuildVersion = "v437"' in (root/'build_identity.go').read_text())
failed=[n for n,v in checks if not v]
print(f'\n{len(checks)-len(failed)}/{len(checks)} passed')
if failed:
    raise SystemExit('failed: '+', '.join(failed))
