-- Cursor Control v320 research-roadmap competitive foundation.
-- Server-authoritative weekly standings and cosmetic-only prestige history.

create table if not exists public.weekly_scores (
  week_key text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  difficulty text not null,
  score bigint not null default 0,
  streak integer not null default 0,
  accuracy double precision not null default 0,
  distance double precision not null default 0,
  targets_hit integer not null default 0,
  achieved_at timestamptz not null default now(),
  primary key (week_key, user_id, difficulty),
  constraint weekly_scores_difficulty check (difficulty in ('OVERALL','EASY','NORMAL','HARD','INSANE','ENDURANCE','SURVIVAL'))
);
create index if not exists weekly_scores_rank_idx on public.weekly_scores (week_key, difficulty, score desc, streak desc, accuracy desc);

create table if not exists public.competitive_seasons (
  season_key text primary key,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  display_name text not null,
  active boolean not null default false
);

create table if not exists public.competitive_awards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  award_key text not null,
  period_key text not null,
  placement integer,
  badge text,
  temporary_title text,
  temporary_frame integer,
  awarded_at timestamptz not null default now(),
  expires_at timestamptz,
  unique(user_id, award_key, period_key)
);
create index if not exists competitive_awards_user_idx on public.competitive_awards(user_id, awarded_at desc);

alter table public.weekly_scores enable row level security;
alter table public.competitive_awards enable row level security;
alter table public.competitive_seasons enable row level security;

-- Edge Functions use the service role. Clients only need to read their own awards.
drop policy if exists "read own competitive awards" on public.competitive_awards;
create policy "read own competitive awards" on public.competitive_awards for select to authenticated using (auth.uid() = user_id);

-- Seasonal definitions are public metadata.
drop policy if exists "read competitive seasons" on public.competitive_seasons;
create policy "read competitive seasons" on public.competitive_seasons for select using (true);
