-- Privacy-minimal analytics intake. Only deploy with an appropriate privacy/consent
-- notice for the audience. The client defaults network analytics OFF.
create table if not exists public.gameplay_analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  received_at timestamptz not null default now(),
  client_at timestamptz,
  event_name text not null,
  mode text,
  fields jsonb not null default '{}'::jsonb
);
create index if not exists gameplay_analytics_event_idx on public.gameplay_analytics_events(event_name, received_at desc);
create index if not exists gameplay_analytics_mode_idx on public.gameplay_analytics_events(mode, received_at desc);
alter table public.gameplay_analytics_events enable row level security;
-- No direct client policies: Edge Function service-role only.
